import {
  AlertTriangle,
  Globe,
  Lock,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  CalendarDays,
  Camera,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Crown,
  Edit3,
  Eye,
  Heart,
  Image,
  Info,
  Lightbulb,
  Mail,
  MapPin,
  MessageCircle,
  PartyPopper,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Share2,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Trash2,
  Utensils,
  Wallet,
  X,
  Menu,
  Home,
  LayoutGrid,
  LogOut,
  PlusCircle,
  User,
} from "lucide-react";

const ICONS = {
  alert: AlertTriangle,
  globe: Globe,
  lock: Lock,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  barChart: BarChart3,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  chef: ChefHat,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  crown: Crown,
  edit: Edit3,
  eye: Eye,
  heart: Heart,
  image: Image,
  info: Info,
  lightbulb: Lightbulb,
  mail: Mail,
  mapPin: MapPin,
  message: MessageCircle,
  partyPopper: PartyPopper,
  phone: Phone,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  share: Share2,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  trash: Trash2,
  utensils: Utensils,
  wallet: Wallet,
  x: X,
  menu: Menu,
  home: Home,
  grid: LayoutGrid,
  logOut: LogOut,
  plusCircle: PlusCircle,
  user: User,
};

export default function AppIcon({
  name,
  size = 18,
  color = "currentColor",
  fill = "none",
  strokeWidth = 2,
  style,
  ...props
}) {
  const Icon = ICONS[name] || Info;
  return (
    <Icon
      aria-hidden="true"
      focusable="false"
      size={size}
      color={color}
      fill={fill}
      strokeWidth={strokeWidth}
      style={{ display: "inline-block", flexShrink: 0, ...style }}
      {...props}
    />
  );
}